all: white.aiff pink1.0.aiff pink1.3.aiff pink1.6.aiff brown.aiff sound
LDFLAGS=-lm
white.aiff: sound
	./sound 0 > $@.uw
	sox -r 44100 $@.uw $@
pink1.0.aiff: sound
	./sound 1 > $@.uw
	sox -r 44100 $@.uw $@
pink1.3.aiff: sound
	./sound 1.3 > $@.uw
	sox -r 44100 $@.uw $@
pink1.6.aiff: sound
	./sound 1.6 > $@.uw
	sox -r 44100 $@.uw $@
brown.aiff: sound
	./sound 2 > $@.uw
	sox -r 44100 $@.uw $@
